apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ocvd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ocvd
    app.kubernetes.io/part-of: byoc-app-zkzx
  name: ocvd
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: ocvd
status:
  loadBalancer: {}
